#spring:
#datasource:

# url: =jdbc:mysql://localhost:3306/itpackaging
#  username: root
#   password: root
#jpa:
# If you want to use data.sql to populate a schema created by Hibernate
#defer-datasource-initialization: true
#generate-ddl: true
#hibernate:
#     ddl-auto: update
#  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#   show-sql: true
#sql:
#     init:
#          mode: always
